[build]
  functions = "functions/"
  publish = "dist/"
  command = "npm run build"

[functions]
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"

[template.environment]
  API_URL = "your Google Maps API endpoint"
  API_TOKEN = "your Google Maps API key"

[[redirects]]
from="/api"
to=".netlify/functions/getapi"
status=200
